import { readFile, access } from 'node:fs/promises';
const required = ['index.html','src/app.js','src/core.js','src/chart.js','src/curriculum.js','src/drills.js','src/events.js','src/data-utils.js','src/styles.css','public/data/manifest.json','README.md'];
for (const f of required) await access(f);
const html = await readFile('index.html','utf8');
if (!html.includes('Forex Lab PH')) throw new Error('Title missing');
const curriculum = await readFile('src/curriculum.js','utf8');
const lessonMatches = [...curriculum.matchAll(/lesson\('m\d+l\d+'/g)];
if (lessonMatches.length < 60) throw new Error(`Expected >=60 lessons; found ${lessonMatches.length}`);
const app = await readFile('src/app.js','utf8');
for (const term of ['Dense drill mode','Trading-session simulator','Historical event challenges','BUY','SELL','NO TRADE','Asia/Manila']) if (!app.includes(term)) throw new Error(`Missing ${term}`);
const downloader = await readFile('scripts/download-history.mjs','utf8');
for (const term of ["timeframe: 'm15'", "'H1'", "'H4'", "priceType: 'bid'"]) if (!downloader.includes(term)) throw new Error(`Downloader missing ${term}`);
const events = await readFile('src/events.js','utf8');
const eventCount = (events.match(/sourceUrl:/g) || []).length;
if (eventCount < 8) throw new Error(`Expected >=8 sourced historical events; found ${eventCount}`);
console.log(`Static checks passed: ${lessonMatches.length} lessons, 4 practice modes, M15/H1/H4 data path, ${eventCount} sourced events.`);
