import { readFile, access } from 'node:fs/promises';
const required = ['index.html','src/app.js','src/core.js','src/chart.js','src/curriculum.js','src/drills.js','src/events.js','src/data-utils.js','src/styles.css','public/data/manifest.json','desktop/main.cjs','desktop/preload.cjs','docs/MAC_APP.md','docs/WINDOWS_APP.md','README.md'];
for (const f of required) await access(f);
const html = await readFile('index.html','utf8');
if (!html.includes('Forex Lab PH')) throw new Error('Title missing');
const curriculum = await readFile('src/curriculum.js','utf8');
const lessonMatches = [...curriculum.matchAll(/lesson\('m\d+l\d+'/g)];
if (lessonMatches.length < 60) throw new Error(`Expected >=60 lessons; found ${lessonMatches.length}`);
const app = await readFile('src/app.js','utf8');
for (const term of ['Dense drill mode','Trading-session simulator','Historical event challenges','BUY','SELL','NO TRADE','Asia/Manila']) if (!app.includes(term)) throw new Error(`Missing ${term}`);
const downloader = await readFile('scripts/download-history.mjs','utf8');
for (const term of ["timeframe: 'm15'", "'H1'", "'H4'", "priceType: 'bid'"]) if (!downloader.includes(term)) throw new Error(`Downloader missing ${term}`);
const events = await readFile('src/events.js','utf8');
const eventCount = (events.match(/sourceUrl:/g) || []).length;
if (eventCount < 8) throw new Error(`Expected >=8 sourced historical events; found ${eventCount}`);
const desktop = await readFile('desktop/main.cjs','utf8');
for (const term of ['forexlab://app/index.html','install-data','market-data','clearCache','releases/latest','setAppUserModelId']) if (!desktop.includes(term)) throw new Error(`Desktop shell missing ${term}`);
const preload = await readFile('desktop/preload.cjs','utf8');
for (const term of ['Install Starter Data','Install Full 6-Pair Data','Check for Updates']) if (!preload.includes(term)) throw new Error(`Desktop UI bridge missing ${term}`);
const pkg = JSON.parse(await readFile('package.json','utf8'));
if (pkg.version !== '0.3.0' || pkg.build?.pkg?.overwriteAction !== 'upgrade') throw new Error('Mac desktop package/update config mismatch');
if (!pkg.scripts?.['desktop:build:win']?.includes('--win nsis zip --x64')) throw new Error('Windows build script missing');
if (pkg.build?.nsis?.guid !== 'E8A7C955-2B4F-4A31-9A12-2C53A0F0B0E4') throw new Error('Windows upgrade GUID changed or missing');
if (pkg.build?.nsis?.oneClick !== false || pkg.build?.nsis?.allowToChangeInstallationDirectory !== false) throw new Error('Windows assisted installer policy mismatch');
if (!String(pkg.build?.win?.artifactName || '').includes('Windows-${arch}')) throw new Error('Windows artifact naming mismatch');
console.log(`Static checks passed: ${lessonMatches.length} lessons, 4 practice modes, macOS + Windows no-Terminal installer paths, M15/H1/H4 data path, ${eventCount} sourced events.`);
